# Generated by Django 3.0.5 on 2021-11-29 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='subCategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='app.SubCategory'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('Event-Creation', 'Event-Creation'), ('Reminder', 'Reminder'), ('User-Following', 'User-Following')], max_length=300)),
                ('isSeen', models.BooleanField(default=False)),
                ('dateCreated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Event')),
                ('fromUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('toUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
