# Generated by Django 3.0.5 on 2021-12-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerfollowing',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
