# Generated by Django 3.0.5 on 2021-12-03 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_promocode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
