# Generated by Django 3.0.5 on 2021-12-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
