# Generated by Django 3.0.5 on 2021-12-03 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_promocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('percentage_decrease', models.FloatField()),
                ('dateCreated', models.DateTimeField(auto_now=True)),
                ('maxNoOfAttendees', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Event')),
                ('usedBy', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
