# Generated by Django 3.0.5 on 2021-12-07 10:03

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_eventlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='links',
            field=djongo.models.fields.JSONField(null=True),
        ),
    ]
