# Generated by Django 3.0.5 on 2021-12-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_extendeduser_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age',
            field=models.CharField(default=25, max_length=3),
        ),
    ]
