# Generated by Django 3.0.5 on 2021-12-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_event_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='age',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='age',
            field=models.CharField(default=25, max_length=3),
        ),
    ]
