# Generated by Django 3.0.5 on 2021-12-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20211207_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='links',
        ),
    ]
