# Generated by Django 3.0.5 on 2021-12-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_survey_surveyresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='timestamp',
        ),
    ]
