# Generated by Django 3.0.5 on 2021-12-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_survey_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
