# Generated by Django 3.0.5 on 2021-12-12 15:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_walletconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField(default=0)),
                ('description', models.CharField(max_length=250)),
                ('startDate', models.DateTimeField()),
                ('venue', models.CharField(default='', max_length=200)),
                ('location', location_field.models.plain.PlainLocationField(default='', max_length=63)),
                ('phones', djongo.models.fields.JSONField()),
                ('image_url', models.URLField(blank=True)),
                ('maxNoOfAttendees', models.IntegerField(default=100)),
                ('noOfViews', models.IntegerField(default=0)),
                ('isHidden', models.BooleanField(default=False)),
                ('eventkey', models.CharField(max_length=20)),
                ('minPercentageToPay', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('createdBy', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GraduationBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('percentagePayed', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('code', models.CharField(max_length=20, unique=True)),
                ('qrcode', models.URLField(null=True)),
                ('has_attended', models.BooleanField(default=False)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('graduationEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.GraduationEvent')),
            ],
        ),
    ]
