# Generated by Django 3.0.5 on 2021-12-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_graduationbooking_graduationevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduationevent',
            name='createdBy',
        ),
        migrations.DeleteModel(
            name='GraduationBooking',
        ),
        migrations.DeleteModel(
            name='GraduationEvent',
        ),
    ]
