# Generated by Django 3.0.5 on 2021-12-12 19:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_graduationevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('percentagePayed', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('code', models.CharField(max_length=20, unique=True)),
                ('qrcode', models.URLField(null=True)),
                ('has_attended', models.BooleanField(default=False)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('graduationEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.GraduationEvent')),
            ],
        ),
    ]
