# Generated by Django 3.0.5 on 2021-12-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_graduationbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='isVirtual',
            field=models.BooleanField(default=False),
        ),
    ]
