# Generated by Django 3.0.5 on 2021-12-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_tag_isvirtual'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isVirtual',
            field=models.BooleanField(default=False),
        ),
    ]
