# Generated by Django 3.0.5 on 2022-02-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_event_isvirtual'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='firebase_uuid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
