# Generated by Django 3.0.5 on 2022-02-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_usher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='age',
        ),
    ]
