# Generated by Django 3.0.5 on 2022-02-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_extendeduser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='dateofbirth',
            field=models.DateTimeField(default='1999-03-12T01:12:00Z'),
        ),
    ]
