# Generated by Django 3.0.5 on 2022-03-30 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_extendeduser_dateofbirth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='type',
        ),
    ]
