# Generated by Django 3.0.5 on 2022-04-16 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_remove_reservation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Event-Creation', 'Event-Creation'), ('Reminder', 'Reminder'), ('User-Following', 'User-Following'), ('Review-Reminder', 'Review-Reminder')], max_length=300),
        ),
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionNo', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Booking')),
            ],
        ),
    ]
