# Generated by Django 3.0.5 on 2022-04-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20220416_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpayment',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
