# Generated by Django 3.0.5 on 2022-04-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_bookingpayment_isverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
