# Generated by Django 3.0.5 on 2022-05-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_booking_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='profile_completed',
            field=models.BooleanField(default=True),
        ),
    ]
