# Generated by Django 3.0.5 on 2022-05-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_extendeduser_profile_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='dateofbirth',
            field=models.DateTimeField(null=True),
        ),
    ]
