# Generated by Django 3.0.5 on 2022-05-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20220510_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='dateofbirth',
            field=models.DateTimeField(default='1999-03-12T01:12:00Z'),
        ),
    ]
