# Generated by Django 3.0.5 on 2022-11-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20221104_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_code',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
    ]
